import type { LangCode } from "@/content/types";
import type { LegalSection } from "@/content/global/marketing/affiliateDisclosureContent";

export type CookiesPolicyContent = {
  kicker: string;
  headline: string;
  effectiveLabel: string;
  effectiveDate: string;
  summary: string;
  sections: LegalSection[];
};

const EN_CONTENT: CookiesPolicyContent = {
  kicker: "Cookie Policy",
  headline: "Cookie Policy",
  effectiveLabel: "Effective date",
  effectiveDate: "2026-01-XX",
  summary:
    "We use cookies for three things: making the site work, understanding how it gets used, and (with your consent) measuring marketing performance. We don't use cookies to track you across other sites for advertising. You can manage cookies through the banner on first visit or your browser settings any time after.",
  sections: [
    {
      title: "Cookie categories",
      body: "Strictly necessary. Required for the site to function — load balancing, security, session continuity, language preference. No consent needed under GDPR for these; they exist to make the site work.",
    },
    {
      title: "Analytics",
      body: "Used to understand how visitors interact with the site, which pages perform, and where we can improve. We use [analytics provider — typically Google Analytics 4 or Plausible] with IP anonymization where required. You can opt out via the cookie banner.",
    },
    {
      title: "Marketing / attribution",
      body: "Used to measure whether marketing efforts (paid, organic, referral) bring qualified visitors. You can opt out via the cookie banner.",
    },
    {
      title: "We do not use",
      body: "Cookie use exclusions:",
      items: [
        "Third-party advertising cookies that follow you across the internet",
        "Behavioral re-targeting cookies for ad networks",
        "Cookies that share personally identifiable information with third parties for marketing",
      ],
    },
    {
      title: "Managing cookies",
      body: "On first visit, you'll see a banner letting you accept or reject categories. After that, you can:",
      items: [
        "Update your choices via the cookie preferences link in the footer",
        "Clear cookies through your browser settings",
        'Use browser-level "Do Not Track" or equivalent settings, which we respect',
      ],
    },
    {
      title: "If you reject analytics and marketing cookies",
      body: "The site still works — we just have less visibility into how it's used.",
    },
    {
      title: "Specific cookies in use",
      body: "[A standard cookie table belongs here in deployment, listing name, purpose, provider, and duration for each cookie used. This page will be auto-generated by the cookie consent platform when deployed.]",
    },
    {
      title: "Updates",
      body: "This policy gets updated as the site evolves. The effective date above changes when it does. For cookie-specific questions: privacy@sigmaa.pro.",
    },
  ],
};

export const cookiesPolicyContentByLang: Record<LangCode, CookiesPolicyContent> = {
  EN: EN_CONTENT,
  FA: {
    kicker: "سیاست کوکی‌ها",
    headline: "سیاست کوکی‌ها",
    effectiveLabel: "تاریخ اجرا",
    effectiveDate: EN_CONTENT.effectiveDate,
    summary: "ما از کوکی‌ها برای سه هدف استفاده می‌کنیم: عملکرد صحیح سایت، درک نحوه استفاده از آن و، با رضایت شما، سنجش عملکرد مارکتینگ. از کوکی‌ها برای دنبال‌کردن شما در سایت‌های دیگر با هدف تبلیغات استفاده نمی‌کنیم. می‌توانید کوکی‌ها را از طریق بنر ورود یا تنظیمات مرورگر مدیریت کنید.",
    sections: [
      { title: "دسته‌بندی کوکی‌ها", body: "ضروری. برای عملکرد سایت لازم‌اند؛ از جمله توزیع بار، امنیت، تداوم نشست و ترجیح زبان. طبق GDPR برای این موارد رضایت جداگانه لازم نیست." },
      { title: "تحلیل", body: "برای درک تعامل بازدیدکنندگان با سایت، عملکرد صفحه‌ها و فرصت‌های بهبود استفاده می‌شود. در صورت نیاز، ناشناس‌سازی IP انجام می‌دهیم. می‌توانید از طریق بنر کوکی انصراف دهید." },
      { title: "مارکتینگ و انتساب", body: "برای سنجش این‌که فعالیت‌های مارکتینگ پولی، ارگانیک و ارجاعی بازدیدکننده واجد شرایط می‌آورند یا نه استفاده می‌شود. می‌توانید از طریق بنر انصراف دهید." },
      { title: "مواردی که استفاده نمی‌کنیم", body: "محدودیت‌های استفاده از کوکی:", items: ["کوکی تبلیغاتی شخص ثالث که شما را در اینترنت دنبال کند", "کوکی بازهدف‌گیری رفتاری برای شبکه‌های تبلیغاتی", "کوکی‌ای که اطلاعات شناسایی شخصی را برای مارکتینگ با طرف ثالث به اشتراک بگذارد"] },
      { title: "مدیریت کوکی‌ها", body: "در اولین بازدید، بنری برای پذیرش یا رد دسته‌ها می‌بینید. پس از آن می‌توانید:", items: ["انتخاب خود را از لینک تنظیمات کوکی در فوتر به‌روزرسانی کنید", "کوکی‌ها را از تنظیمات مرورگر پاک کنید", "تنظیمات «ردیابی نکن» مرورگر یا معادل آن را فعال کنید؛ ما به آن احترام می‌گذاریم"] },
      { title: "اگر کوکی‌های تحلیل و مارکتینگ را رد کنید", body: "سایت همچنان کار می‌کند؛ فقط دید کمتری نسبت به نحوه استفاده از آن خواهیم داشت." },
      { title: "کوکی‌های مشخص مورد استفاده", body: "جدول استاندارد کوکی‌ها در زمان استقرار اضافه می‌شود و نام، هدف، ارائه‌دهنده و مدت هر کوکی را نشان می‌دهد." },
      { title: "به‌روزرسانی‌ها", body: "با تکامل سایت، این سیاست نیز به‌روزرسانی می‌شود. تاریخ اجرا هنگام تغییر اصلاح خواهد شد. پرسش‌های مربوط به کوکی: privacy@sigmaa.pro." },
    ],
  },
  ZH: {
    kicker: "Cookie 政策",
    headline: "Cookie 政策",
    effectiveLabel: "生效日期",
    effectiveDate: EN_CONTENT.effectiveDate,
    summary: "我们使用 Cookie 只有三个目的：让网站正常运行、了解网站使用情况，以及在您同意的情况下衡量营销效果。我们不会使用 Cookie 在其他网站上进行广告跟踪。您可以通过首次访问时的提示或浏览器设置管理 Cookie。",
    sections: [
      { title: "Cookie 类别", body: "严格必要。网站运行所需，包括负载均衡、安全、会话连续性和语言偏好。根据 GDPR，这类 Cookie 无需单独同意。" },
      { title: "分析", body: "用于了解访客如何使用网站、哪些页面表现良好以及我们可以改进的地方。需要时我们会进行 IP 匿名化，您可以通过 Cookie 提示选择退出。" },
      { title: "营销与归因", body: "用于衡量付费、自然和推荐营销是否带来合格访客。您可以通过 Cookie 提示选择退出。" },
      { title: "我们不使用的 Cookie", body: "排除项：", items: ["跨互联网跟踪您的第三方广告 Cookie", "广告网络使用的行为再营销 Cookie", "为营销目的向第三方分享可识别个人信息的 Cookie"] },
      { title: "管理 Cookie", body: "首次访问时，您可以在提示中接受或拒绝类别。之后您可以：", items: ["通过页脚的 Cookie 偏好链接更新选择", "通过浏览器设置清除 Cookie", "使用我们尊重的“请勿跟踪”或同类浏览器设置"] },
      { title: "如果拒绝分析和营销 Cookie", body: "网站仍会正常运行，只是我们对使用方式的了解会减少。" },
      { title: "正在使用的具体 Cookie", body: "部署时会加入标准 Cookie 表，列出每个 Cookie 的名称、用途、提供方和期限。" },
      { title: "更新", body: "网站发展时，本政策也会更新。发生变化时，上方生效日期会更新。Cookie 问题请联系：privacy@sigmaa.pro。" },
    ],
  },
  ES: {
    kicker: "Política de cookies",
    headline: "Política de cookies",
    effectiveLabel: "Fecha de entrada en vigor",
    effectiveDate: EN_CONTENT.effectiveDate,
    summary: "Usamos cookies para tres fines: hacer funcionar el sitio, entender cómo se utiliza y, con tu consentimiento, medir el rendimiento del marketing. No usamos cookies para seguirte por otros sitios con fines publicitarios. Puedes gestionarlas mediante el banner inicial o la configuración del navegador.",
    sections: [
      { title: "Categorías de cookies", body: "Estrictamente necesarias. Son necesarias para que el sitio funcione: balanceo, seguridad, continuidad de sesión y preferencia de idioma. El RGPD no exige consentimiento para estas cookies." },
      { title: "Analítica", body: "Se utiliza para entender cómo interactúan los visitantes, qué páginas funcionan y dónde podemos mejorar. Anonimizamos la IP cuando es necesario y puedes rechazar estas cookies desde el banner." },
      { title: "Marketing y atribución", body: "Se utilizan para medir si las acciones de marketing pagadas, orgánicas o de referencia atraen visitantes cualificados. Puedes rechazarlas desde el banner." },
      { title: "Lo que no usamos", body: "Exclusiones:", items: ["Cookies publicitarias de terceros que te sigan por internet", "Cookies de retargeting conductual para redes publicitarias", "Cookies que compartan información personal identificable con terceros para marketing"] },
      { title: "Gestión de cookies", body: "En la primera visita verás un banner para aceptar o rechazar categorías. Después puedes:", items: ["Actualizar tus elecciones desde el enlace de preferencias del pie de página", "Borrar cookies desde la configuración del navegador", "Usar la opción “No rastrear” del navegador, que respetamos"] },
      { title: "Si rechazas cookies de analítica y marketing", body: "El sitio seguirá funcionando; simplemente tendremos menos visibilidad sobre su uso." },
      { title: "Cookies concretas en uso", body: "En producción se añadirá una tabla estándar con nombre, finalidad, proveedor y duración de cada cookie." },
      { title: "Actualizaciones", body: "Esta política se actualiza a medida que evoluciona el sitio. La fecha de entrada en vigor cambiará cuando corresponda. Preguntas: privacy@sigmaa.pro." },
    ],
  },
  RU: {
    kicker: "Политика cookies",
    headline: "Политика cookies",
    effectiveLabel: "Дата вступления в силу",
    effectiveDate: EN_CONTENT.effectiveDate,
    summary: "Мы используем cookies для трёх целей: чтобы сайт работал, понимать его использование и, с вашего согласия, измерять эффективность маркетинга. Мы не используем cookies для рекламного отслеживания на других сайтах. Управлять ими можно через баннер при первом посещении или настройки браузера.",
    sections: [
      { title: "Категории cookies", body: "Строго необходимые. Они нужны для работы сайта: балансировки, безопасности, продолжения сессии и выбора языка. Для них отдельное согласие по GDPR не требуется." },
      { title: "Аналитика", body: "Помогает понять взаимодействие посетителей с сайтом, эффективность страниц и возможности улучшения. При необходимости мы анонимизируем IP; отказаться можно через баннер cookies." },
      { title: "Маркетинг и атрибуция", body: "Помогает измерять, приводят ли платные, органические и реферальные активности качественных посетителей. Отказ доступен через баннер." },
      { title: "Что мы не используем", body: "Исключения:", items: ["Сторонние рекламные cookies, отслеживающие вас в интернете", "Поведенческие cookies ретаргетинга рекламных сетей", "Cookies, передающие третьим сторонам персональные данные для маркетинга"] },
      { title: "Управление cookies", body: "При первом посещении баннер позволяет принять или отклонить категории. После этого можно:", items: ["Изменить выбор через ссылку настроек cookies в футере", "Очистить cookies в настройках браузера", "Использовать режим “Do Not Track”, который мы уважаем"] },
      { title: "Если вы отклоните аналитические и маркетинговые cookies", body: "Сайт продолжит работать, но у нас будет меньше информации о его использовании." },
      { title: "Конкретные используемые cookies", body: "При запуске будет добавлена стандартная таблица с названием, целью, провайдером и сроком действия каждой cookie." },
      { title: "Обновления", body: "Политика обновляется по мере развития сайта. При изменениях обновляется дата вступления в силу. Вопросы: privacy@sigmaa.pro." },
    ],
  },
  AR: {
    kicker: "سياسة ملفات الارتباط",
    headline: "سياسة ملفات الارتباط",
    effectiveLabel: "تاريخ السريان",
    effectiveDate: EN_CONTENT.effectiveDate,
    summary: "نستخدم ملفات الارتباط لثلاثة أغراض: تشغيل الموقع، فهم طريقة استخدامه، وقياس أداء التسويق بموافقتك. لا نستخدمها لتتبعك عبر مواقع أخرى لأغراض إعلانية. يمكنك إدارتها من خلال الإشعار الأول أو إعدادات المتصفح.",
    sections: [
      { title: "فئات ملفات الارتباط", body: "ضرورية تماماً. تلزم لتشغيل الموقع، بما في ذلك موازنة الحمل والأمان واستمرارية الجلسة وتفضيل اللغة. لا يتطلب GDPR موافقة منفصلة عليها." },
      { title: "التحليلات", body: "تُستخدم لفهم تفاعل الزوار وأداء الصفحات ومجالات التحسين. نُخفي هوية عناوين IP عند الحاجة، ويمكنك إلغاء هذه الملفات من الإشعار." },
      { title: "التسويق والإسناد", body: "تُستخدم لقياس ما إذا كانت جهود التسويق المدفوعة أو العضوية أو الإحالات تجلب زواراً مؤهلين. يمكنك إلغاءها من الإشعار." },
      { title: "ما لا نستخدمه", body: "الاستثناءات:", items: ["ملفات إعلانية من أطراف ثالثة تتبعك عبر الإنترنت", "ملفات إعادة الاستهداف السلوكي لشبكات الإعلانات", "ملفات تشارك معلومات تعريف شخصية مع أطراف ثالثة للتسويق"] },
      { title: "إدارة ملفات الارتباط", body: "في الزيارة الأولى يظهر إشعار لقبول الفئات أو رفضها. بعد ذلك يمكنك:", items: ["تحديث اختياراتك من رابط تفضيلات ملفات الارتباط في التذييل", "حذف الملفات من إعدادات المتصفح", "استخدام إعداد “عدم التتبع” الذي نحترمه"] },
      { title: "إذا رفضت ملفات التحليلات والتسويق", body: "سيستمر الموقع في العمل، لكن ستكون لدينا رؤية أقل حول طريقة استخدامه." },
      { title: "ملفات الارتباط المستخدمة تحديداً", body: "ستُضاف عند الإطلاق جداول قياسية توضح اسم كل ملف وغرضه ومزوّده ومدته." },
      { title: "التحديثات", body: "تُحدّث هذه السياسة مع تطور الموقع، ويتغير تاريخ السريان عند التعديل. للاستفسارات: privacy@sigmaa.pro." },
    ],
  },
};
