import type { LangCode } from "@/content/types";
import type { LegalSection } from "@/content/global/marketing/affiliateDisclosureContent";

export type CookiesPolicyContent = {
  kicker: string;
  headline: string;
  effectiveLabel: string;
  effectiveDate: string;
  summary: string;
  sections: LegalSection[];
};

const EN_CONTENT: CookiesPolicyContent = {
  kicker: "Cookie Policy",
  headline: "Cookie Policy",
  effectiveLabel: "Effective date",
  effectiveDate: "2026-01-XX",
  summary:
    "We use cookies for three things: making the site work, understanding how it gets used, and (with your consent) measuring marketing performance. We don't use cookies to track you across other sites for advertising. You can manage cookies through the banner on first visit or your browser settings any time after.",
  sections: [
    {
      title: "Cookie categories",
      body: "Strictly necessary. Required for the site to function — load balancing, security, session continuity, language preference. No consent needed under GDPR for these; they exist to make the site work.",
    },
    {
      title: "Analytics",
      body: "Used to understand how visitors interact with the site, which pages perform, and where we can improve. We use [analytics provider — typically Google Analytics 4 or Plausible] with IP anonymization where required. You can opt out via the cookie banner.",
    },
    {
      title: "Marketing / attribution",
      body: "Used to measure whether marketing efforts (paid, organic, referral) bring qualified visitors. You can opt out via the cookie banner.",
    },
    {
      title: "We do not use",
      body: "Cookie use exclusions:",
      items: [
        "Third-party advertising cookies that follow you across the internet",
        "Behavioral re-targeting cookies for ad networks",
        "Cookies that share personally identifiable information with third parties for marketing",
      ],
    },
    {
      title: "Managing cookies",
      body: "On first visit, you'll see a banner letting you accept or reject categories. After that, you can:",
      items: [
        "Update your choices via the cookie preferences link in the footer",
        "Clear cookies through your browser settings",
        'Use browser-level "Do Not Track" or equivalent settings, which we respect',
      ],
    },
    {
      title: "If you reject analytics and marketing cookies",
      body: "The site still works — we just have less visibility into how it's used.",
    },
    {
      title: "Specific cookies in use",
      body: "[A standard cookie table belongs here in deployment, listing name, purpose, provider, and duration for each cookie used. This page will be auto-generated by the cookie consent platform when deployed.]",
    },
    {
      title: "Updates",
      body: "This policy gets updated as the site evolves. The effective date above changes when it does. For cookie-specific questions: privacy@sigmaa.pro.",
    },
  ],
};

export const cookiesPolicyContentByLang: Record<LangCode, CookiesPolicyContent> = {
  EN: EN_CONTENT,
  TR: EN_CONTENT,
  FA: EN_CONTENT,
  ZH: EN_CONTENT,
  ES: EN_CONTENT,
  RU: EN_CONTENT,
  AR: EN_CONTENT,
};
