// Mobile slide-over navigation — localized section titles & links (homepage).

import type { Localized } from "../_contentLocales";
import type { MobileNavSheetStrings } from "../types";

export const mobileNavSheetContent: Localized<MobileNavSheetStrings> = {
  en: {
    sheetAriaLabel: "Mobile navigation",
    sectionCore: "Core",
    sectionLocations: "Locations",
    sectionServices: "Services",
    sectionInsights: "Insights",
    sectionCompany: "Company",
    linkGrowthEngine: "Growth Engine",
    linkKolMarketing: "KOL Marketing",
    linkLiquidity: "Liquidity",
    linkFeatured: "Featured",
    linkCryptoMarketing101: "Crypto Marketing 101",
  },
  fa: {
    sheetAriaLabel: "منوی موبایل",
    sectionCore: "هسته",
    sectionLocations: "مناطق",
    sectionServices: "خدمات",
    sectionInsights: "بینش‌ها",
    sectionCompany: "شرکت",
    linkGrowthEngine: "موتور رشد",
    linkKolMarketing: "بازاریابی KOL",
    linkLiquidity: "نقدینگی",
    linkFeatured: "ویژه",
    linkCryptoMarketing101: "بازاریابی رمزارز ۱۰۱",
  },
  tr: {
    sheetAriaLabel: "Mobil gezinme",
    sectionCore: "Çekirdek",
    sectionLocations: "Bölgeler",
    sectionServices: "Hizmetler",
    sectionInsights: "İçgörüler",
    sectionCompany: "Şirket",
    linkGrowthEngine: "Büyüme Motoru",
    linkKolMarketing: "KOL Pazarlama",
    linkLiquidity: "Likidite",
    linkFeatured: "Öne çıkan",
    linkCryptoMarketing101: "Kripto Pazarlama 101",
  },
  zh: {
    sheetAriaLabel: "移动端导航",
    sectionCore: "核心",
    sectionLocations: "地区",
    sectionServices: "服务",
    sectionInsights: "洞察",
    sectionCompany: "公司",
    linkGrowthEngine: "增长引擎",
    linkKolMarketing: "KOL 营销",
    linkLiquidity: "流动性",
    linkFeatured: "精选",
    linkCryptoMarketing101: "加密营销入门",
  },
  es: {
    sheetAriaLabel: "Navegación móvil",
    sectionCore: "Núcleo",
    sectionLocations: "Ubicaciones",
    sectionServices: "Servicios",
    sectionInsights: "Insights",
    sectionCompany: "Empresa",
    linkGrowthEngine: "Motor de crecimiento",
    linkKolMarketing: "Marketing KOL",
    linkLiquidity: "Liquidez",
    linkFeatured: "Destacado",
    linkCryptoMarketing101: "Marketing cripto 101",
  },
  ru: {
    sheetAriaLabel: "Мобильная навигация",
    sectionCore: "Ядро",
    sectionLocations: "Локации",
    sectionServices: "Сервисы",
    sectionInsights: "Инсайты",
    sectionCompany: "Компания",
    linkGrowthEngine: "Движок роста",
    linkKolMarketing: "KOL-маркетинг",
    linkLiquidity: "Ликвидность",
    linkFeatured: "Избранное",
    linkCryptoMarketing101: "Криптомаркетинг 101",
  },
  ar: {
    sheetAriaLabel: "التنقّل على الجوال",
    sectionCore: "الأساسي",
    sectionLocations: "المواقع",
    sectionServices: "الخدمات",
    sectionInsights: "الرؤى",
    sectionCompany: "الشركة",
    linkGrowthEngine: "محرك النمو",
    linkKolMarketing: "تسويق KOL",
    linkLiquidity: "السيولة",
    linkFeatured: "مختارات",
    linkCryptoMarketing101: "تسويق العملات المشفرة 101",
  },
};
