import type { LangCode } from "@/content/types";

export type PartnerIntentCopy = {
  title: string;
  body: string;
  companyLabel: string;
  companyDescription: string;
  kolLabel: string;
  kolDescription: string;
  companyFormTitle: string;
  companyFormDescription: string;
  kolFormTitle: string;
  kolFormDescription: string;
  nameLabel: string;
  companyNameLabel: string;
  emailLabel: string;
  websiteOptionalLabel: string;
  descriptionLabel: string;
  roleLabel: string;
  selectRolesHint: string;
  roleKol: string;
  roleIb: string;
  roleTrader: string;
  socialOptionalLabel: string;
  countryOptionalLabel: string;
  performanceOptionalLabel: string;
  attachFileLabel: string;
  removeFileLabel: string;
  backLabel: string;
  closeLabel: string;
  submitLabel: string;
  sendingLabel: string;
  successMessage: string;
  errorMessage: string;
  requiredMessage: string;
  invalidEmailMessage: string;
  fileTooLargeMessage: string;
  unsupportedFileTypeMessage: string;
  backdropCloseAria: string;
};

export const partnerIntentCopyByLang: Record<LangCode, PartnerIntentCopy> = {
  EN: {
    title: "How do you want to partner with Sigma?",
    body: "Choose the path that best matches your role so we can route your request correctly.",
    companyLabel: "Company",
    companyDescription:
      "For exchanges, brokers, protocols, fintech platforms, funds, and institutional partners.",
    kolLabel: "KOL / IB / Trader",
    kolDescription:
      "For creators, affiliates, IBs, trading communities, VIPs, whales, and active traders.",
    companyFormTitle: "Company Partnership Request",
    companyFormDescription:
      "Tell us about your company. Detailed form fields will be added in the next implementation pass.",
    kolFormTitle: "KOL / IB / Trader Application",
    kolFormDescription:
      "Tell us about your role in the market. Detailed form fields will be added in the next implementation pass.",
    nameLabel: "Name & Last Name",
    companyNameLabel: "Company Name",
    emailLabel: "Email",
    websiteOptionalLabel: "Website Address (optional)",
    descriptionLabel: "Description",
    roleLabel: "Role",
    selectRolesHint: "Select one or more roles",
    roleKol: "KOL",
    roleIb: "IB",
    roleTrader: "Trader",
    socialOptionalLabel: "Social Media Link (optional)",
    countryOptionalLabel: "Country (optional)",
    performanceOptionalLabel: "Performance screenshot (optional)",
    attachFileLabel: "Attach file",
    removeFileLabel: "Remove file",
    backLabel: "Back",
    closeLabel: "Close",
    submitLabel: "Submit",
    sendingLabel: "Sending...",
    successMessage: "Thank you. Your request has been received. The Sigma team will review it and get back to you.",
    errorMessage: "Something went wrong. Please try again or contact BD@sigmaa.pro directly.",
    requiredMessage: "This field is required.",
    invalidEmailMessage: "Please enter a valid email.",
    fileTooLargeMessage: "File is too large. Maximum size is 5MB.",
    unsupportedFileTypeMessage: "Unsupported file type.",
    backdropCloseAria: "Close partner intent modal",
  },
  FA: {
    title: "چطور می‌خواهید با Sigma همکاری کنید؟",
    body: "مسیری را انتخاب کنید که با نقش شما هماهنگ‌تر است تا درخواست شما درست هدایت شود.",
    companyLabel: "Company",
    companyDescription: "برای صرافی‌ها، بروکرها، پروتکل‌ها، پلتفرم‌های فین‌تک، صندوق‌ها و شرکای سازمانی.",
    kolLabel: "KOL / IB / Trader",
    kolDescription: "برای کریتور‌ها، افیلیت‌ها، IBها، کامیونیتی‌های ترید، VIPها، نهنگ‌ها و تریدرهای فعال.",
    companyFormTitle: "درخواست همکاری شرکتی",
    companyFormDescription: "درباره شرکت خود به ما بگویید. فیلدهای دقیق فرم در مرحله بعدی اضافه می‌شوند.",
    kolFormTitle: "درخواست KOL / IB / Trader",
    kolFormDescription: "درباره نقش خود در بازار به ما بگویید. فیلدهای دقیق فرم در مرحله بعدی اضافه می‌شوند.",
    nameLabel: "نام و نام خانوادگی",
    companyNameLabel: "نام شرکت",
    emailLabel: "ایمیل",
    websiteOptionalLabel: "آدرس وب‌سایت (اختیاری)",
    descriptionLabel: "توضیحات",
    roleLabel: "نقش",
    selectRolesHint: "یک یا چند نقش را انتخاب کنید",
    roleKol: "KOL",
    roleIb: "IB",
    roleTrader: "Trader",
    socialOptionalLabel: "لینک شبکه اجتماعی (اختیاری)",
    countryOptionalLabel: "کشور (اختیاری)",
    performanceOptionalLabel: "اسکرین‌شات عملکرد (اختیاری)",
    attachFileLabel: "پیوست فایل",
    removeFileLabel: "حذف فایل",
    backLabel: "بازگشت",
    closeLabel: "بستن",
    submitLabel: "ارسال",
    sendingLabel: "در حال ارسال…",
    successMessage: "ممنون. درخواست شما دریافت شد. تیم Sigma آن را بررسی می‌کند و با شما تماس می‌گیرد.",
    errorMessage: "مشکلی پیش آمد. لطفاً دوباره تلاش کنید یا مستقیم با BD@sigmaa.pro تماس بگیرید.",
    requiredMessage: "این فیلد الزامی است.",
    invalidEmailMessage: "لطفاً یک ایمیل معتبر وارد کنید.",
    fileTooLargeMessage: "فایل بیش از حد بزرگ است. حداکثر حجم ۵MB است.",
    unsupportedFileTypeMessage: "نوع فایل پشتیبانی نمی‌شود.",
    backdropCloseAria: "بستن مودال مسیر همکاری",
  },
  AR: {
    title: "كيف تريد التعاون مع Sigma؟",
    body: "اختر المسار الأقرب إلى دورك حتى نتمكن من توجيه طلبك بشكل صحيح.",
    companyLabel: "Company",
    companyDescription: "للمنصات، الوسطاء، البروتوكولات، منصات التكنولوجيا المالية، الصناديق، والشركاء المؤسسيين.",
    kolLabel: "KOL / IB / Trader",
    kolDescription:
      "لصنّاع المحتوى، الشركاء التابعين، IBs، مجتمعات التداول، كبار العملاء، الحيتان، والمتداولين النشطين.",
    companyFormTitle: "طلب شراكة لشركة",
    companyFormDescription: "أخبرنا عن شركتك. ستتم إضافة حقول النموذج التفصيلية في مرحلة التنفيذ التالية.",
    kolFormTitle: "طلب KOL / IB / Trader",
    kolFormDescription: "أخبرنا عن دورك في السوق. ستتم إضافة حقول النموذج التفصيلية في مرحلة التنفيذ التالية.",
    nameLabel: "الاسم واللقب",
    companyNameLabel: "اسم الشركة",
    emailLabel: "البريد الإلكتروني",
    websiteOptionalLabel: "عنوان الموقع الإلكتروني (اختياري)",
    descriptionLabel: "الوصف",
    roleLabel: "الدور",
    selectRolesHint: "اختر دورًا واحدًا أو أكثر",
    roleKol: "KOL",
    roleIb: "IB",
    roleTrader: "Trader",
    socialOptionalLabel: "رابط وسائل التواصل الاجتماعي (اختياري)",
    countryOptionalLabel: "الدولة (اختياري)",
    performanceOptionalLabel: "لقطة شاشة للأداء (اختياري)",
    attachFileLabel: "إرفاق ملف",
    removeFileLabel: "إزالة الملف",
    backLabel: "رجوع",
    closeLabel: "إغلاق",
    submitLabel: "إرسال",
    sendingLabel: "جارٍ الإرسال…",
    successMessage: "شكرًا لك. تم استلام طلبك. سيقوم فريق Sigma بمراجعته والرد عليك.",
    errorMessage: "حدث خطأ ما. يرجى المحاولة مرة أخرى أو التواصل مباشرة عبر BD@sigmaa.pro.",
    requiredMessage: "هذا الحقل مطلوب.",
    invalidEmailMessage: "يرجى إدخال بريد إلكتروني صالح.",
    fileTooLargeMessage: "الملف كبير جدًا. الحد الأقصى هو 5MB.",
    unsupportedFileTypeMessage: "نوع الملف غير مدعوم.",
    backdropCloseAria: "إغلاق نافذة مسار الشراكة",
  },
  TR: {
    title: "Sigma ile nasıl iş birliği yapmak istiyorsunuz?",
    body: "Talebinizi doğru şekilde yönlendirebilmemiz için rolünüze en uygun yolu seçin.",
    companyLabel: "Company",
    companyDescription: "Borsalar, brokerlar, protokoller, fintech platformları, fonlar ve kurumsal partnerler için.",
    kolLabel: "KOL / IB / Trader",
    kolDescription: "Creator’lar, affiliate’ler, IB’ler, trading toplulukları, VIP’ler, whale’lar ve aktif trader’lar için.",
    companyFormTitle: "Şirket Ortaklık Talebi",
    companyFormDescription: "Bize şirketinizden bahsedin. Detaylı form alanları bir sonraki uygulama aşamasında eklenecek.",
    kolFormTitle: "KOL / IB / Trader Başvurusu",
    kolFormDescription: "Bize piyasadaki rolünüzden bahsedin. Detaylı form alanları bir sonraki uygulama aşamasında eklenecek.",
    nameLabel: "Ad ve Soyad",
    companyNameLabel: "Şirket Adı",
    emailLabel: "E-posta",
    websiteOptionalLabel: "Web Sitesi Adresi (opsiyonel)",
    descriptionLabel: "Açıklama",
    roleLabel: "Rol",
    selectRolesHint: "Bir veya daha fazla rol seçin",
    roleKol: "KOL",
    roleIb: "IB",
    roleTrader: "Trader",
    socialOptionalLabel: "Sosyal Medya Linki (opsiyonel)",
    countryOptionalLabel: "Ülke (opsiyonel)",
    performanceOptionalLabel: "Performans ekran görüntüsü (opsiyonel)",
    attachFileLabel: "Dosya ekle",
    removeFileLabel: "Dosyayı kaldır",
    backLabel: "Geri",
    closeLabel: "Kapat",
    submitLabel: "Gönder",
    sendingLabel: "Gönderiliyor…",
    successMessage: "Teşekkürler. Talebiniz alındı. Sigma ekibi inceleyip size geri dönecek.",
    errorMessage: "Bir şeyler ters gitti. Lütfen tekrar deneyin veya doğrudan BD@sigmaa.pro ile iletişime geçin.",
    requiredMessage: "Bu alan zorunludur.",
    invalidEmailMessage: "Lütfen geçerli bir e-posta girin.",
    fileTooLargeMessage: "Dosya çok büyük. Maksimum boyut 5MB.",
    unsupportedFileTypeMessage: "Desteklenmeyen dosya türü.",
    backdropCloseAria: "İş birliği modalını kapat",
  },
  RU: {
    title: "Как вы хотите сотрудничать с Sigma?",
    body: "Выберите путь, который лучше всего соответствует вашей роли, чтобы мы правильно направили ваш запрос.",
    companyLabel: "Company",
    companyDescription: "Для бирж, брокеров, протоколов, финтех-платформ, фондов и институциональных партнёров.",
    kolLabel: "KOL / IB / Trader",
    kolDescription:
      "Для креаторов, аффилиатов, IB, трейдерских сообществ, VIP-клиентов, крупных трейдеров и активных участников рынка.",
    companyFormTitle: "Запрос на партнёрство для компании",
    companyFormDescription: "Расскажите нам о вашей компании. Подробные поля формы будут добавлены на следующем этапе.",
    kolFormTitle: "Заявка KOL / IB / Trader",
    kolFormDescription: "Расскажите нам о вашей роли на рынке. Подробные поля формы будут добавлены на следующем этапе.",
    nameLabel: "Имя и фамилия",
    companyNameLabel: "Название компании",
    emailLabel: "Email",
    websiteOptionalLabel: "Адрес сайта (необязательно)",
    descriptionLabel: "Описание",
    roleLabel: "Роль",
    selectRolesHint: "Выберите одну или несколько ролей",
    roleKol: "KOL",
    roleIb: "IB",
    roleTrader: "Trader",
    socialOptionalLabel: "Ссылка на социальные сети (необязательно)",
    countryOptionalLabel: "Страна (необязательно)",
    performanceOptionalLabel: "Скриншот результатов (необязательно)",
    attachFileLabel: "Прикрепить файл",
    removeFileLabel: "Удалить файл",
    backLabel: "Назад",
    closeLabel: "Закрыть",
    submitLabel: "Отправить",
    sendingLabel: "Отправка…",
    successMessage: "Спасибо. Ваш запрос получен. Команда Sigma рассмотрит его и свяжется с вами.",
    errorMessage: "Что-то пошло не так. Попробуйте ещё раз или свяжитесь напрямую с BD@sigmaa.pro.",
    requiredMessage: "Это поле обязательно.",
    invalidEmailMessage: "Введите корректный email.",
    fileTooLargeMessage: "Файл слишком большой. Максимальный размер — 5MB.",
    unsupportedFileTypeMessage: "Тип файла не поддерживается.",
    backdropCloseAria: "Закрыть модальное окно пути партнёрства",
  },
  ZH: {
    title: "您希望如何与 Sigma 合作？",
    body: "请选择最符合您角色的路径，以便我们正确处理您的请求。",
    companyLabel: "Company",
    companyDescription: "适用于交易所、经纪商、协议、金融科技平台、基金和机构合作伙伴。",
    kolLabel: "KOL / IB / Trader",
    kolDescription: "适用于创作者、联盟合作伙伴、IB、交易社区、VIP、巨鲸用户和活跃交易者。",
    companyFormTitle: "公司合作请求",
    companyFormDescription: "请告诉我们您的公司情况。详细表单字段将在下一轮实施中添加。",
    kolFormTitle: "KOL / IB / Trader 申请",
    kolFormDescription: "请告诉我们您在市场中的角色。详细表单字段将在下一轮实施中添加。",
    nameLabel: "姓名",
    companyNameLabel: "公司名称",
    emailLabel: "邮箱",
    websiteOptionalLabel: "网站地址（可选）",
    descriptionLabel: "描述",
    roleLabel: "角色",
    selectRolesHint: "选择一个或多个角色",
    roleKol: "KOL",
    roleIb: "IB",
    roleTrader: "Trader",
    socialOptionalLabel: "社交媒体链接（可选）",
    countryOptionalLabel: "国家/地区（可选）",
    performanceOptionalLabel: "表现截图（可选）",
    attachFileLabel: "上传文件",
    removeFileLabel: "移除文件",
    backLabel: "返回",
    closeLabel: "关闭",
    submitLabel: "提交",
    sendingLabel: "正在发送…",
    successMessage: "谢谢。您的请求已收到。Sigma 团队会审核并与您联系。",
    errorMessage: "出现错误。请重试或直接联系 BD@sigmaa.pro。",
    requiredMessage: "此字段为必填项。",
    invalidEmailMessage: "请输入有效的邮箱地址。",
    fileTooLargeMessage: "文件过大。最大大小为 5MB。",
    unsupportedFileTypeMessage: "不支持的文件类型。",
    backdropCloseAria: "关闭合作路径弹窗",
  },
  ES: {
    title: "¿Cómo quieres asociarte con Sigma?",
    body: "Elige el camino que mejor encaje con tu rol para que podamos dirigir tu solicitud correctamente.",
    companyLabel: "Company",
    companyDescription: "Para exchanges, brokers, protocolos, plataformas fintech, fondos y socios institucionales.",
    kolLabel: "KOL / IB / Trader",
    kolDescription: "Para creadores, afiliados, IBs, comunidades de trading, VIPs, whales y traders activos.",
    companyFormTitle: "Solicitud de partnership para empresa",
    companyFormDescription:
      "Cuéntanos sobre tu empresa. Los campos detallados del formulario se añadirán en la siguiente fase de implementación.",
    kolFormTitle: "Solicitud KOL / IB / Trader",
    kolFormDescription:
      "Cuéntanos sobre tu rol en el mercado. Los campos detallados del formulario se añadirán en la siguiente fase de implementación.",
    nameLabel: "Nombre y apellido",
    companyNameLabel: "Nombre de la empresa",
    emailLabel: "Email",
    websiteOptionalLabel: "Sitio web (opcional)",
    descriptionLabel: "Descripción",
    roleLabel: "Rol",
    selectRolesHint: "Selecciona uno o más roles",
    roleKol: "KOL",
    roleIb: "IB",
    roleTrader: "Trader",
    socialOptionalLabel: "Link de redes sociales (opcional)",
    countryOptionalLabel: "País (opcional)",
    performanceOptionalLabel: "Captura de rendimiento (opcional)",
    attachFileLabel: "Adjuntar archivo",
    removeFileLabel: "Eliminar archivo",
    backLabel: "Atrás",
    closeLabel: "Cerrar",
    submitLabel: "Enviar",
    sendingLabel: "Enviando…",
    successMessage: "Gracias. Hemos recibido tu solicitud. El equipo de Sigma la revisará y se pondrá en contacto contigo.",
    errorMessage: "Algo salió mal. Inténtalo de nuevo o contacta directamente con BD@sigmaa.pro.",
    requiredMessage: "Este campo es obligatorio.",
    invalidEmailMessage: "Introduce un email válido.",
    fileTooLargeMessage: "El archivo es demasiado grande. El tamaño máximo es 5MB.",
    unsupportedFileTypeMessage: "Tipo de archivo no compatible.",
    backdropCloseAria: "Cerrar modal de intención de partnership",
  },
};
