import type { LangCode } from "@/content/types";
import type { FinalServiceSlug } from "./finalServices";

export type ServiceUiCopy = {
  home: string;
  services: string;
  introduction: string;
  service: string;
  primaryCapabilities: string;
  routes: string;
  exploreRoute: string;
  serviceDisclaimer: string;
  placeholderNote: string;
  serviceDetail: string;
  reference: string;
  detailsAtAGlance: string;
  nextStep: string;
  buildGrowthInfrastructure: string;
  shareProductMarketsConstraints: string;
  talkToSigma: string;
  exploreAllServices: string;
  callsToAction: string;
};

export const serviceUiByLang: Record<LangCode, ServiceUiCopy> = {
  EN: {
    home: "Home",
    services: "Services",
    introduction: "Introduction",
    service: "Service",
    primaryCapabilities: "Primary capabilities",
    routes: "Routes",
    exploreRoute: "Explore route",
    serviceDisclaimer: "Service disclaimer",
    placeholderNote: "Full service content and final page design will be added after the approved service template is completed.",
    serviceDetail: "Service detail",
    reference: "Reference",
    detailsAtAGlance: "Service details at a glance",
    nextStep: "Next step",
    buildGrowthInfrastructure: "Build the right growth infrastructure with Sigma",
    shareProductMarketsConstraints: "Share your product, markets and constraints so Sigma can map the right operating path.",
    talkToSigma: "Talk to Sigma",
    exploreAllServices: "Explore all services",
    callsToAction: "Calls to action",
  },
  FA: {
    home: "خانه",
    services: "خدمات",
    introduction: "مقدمه",
    service: "خدمت",
    primaryCapabilities: "قابلیت‌های اصلی",
    routes: "مسیرها",
    exploreRoute: "مشاهده مسیر",
    serviceDisclaimer: "سلب مسئولیت خدمات",
    placeholderNote: "محتوای کامل خدمت و طراحی نهایی صفحه پس از تکمیل قالب تأییدشده خدمت اضافه می‌شود.",
    serviceDetail: "جزئیات خدمت",
    reference: "مرجع",
    detailsAtAGlance: "خلاصه جزئیات خدمت",
    nextStep: "گام بعدی",
    buildGrowthInfrastructure: "زیرساخت رشد مناسب را با Sigma بسازید",
    shareProductMarketsConstraints: "محصول، بازارها و محدودیت‌های خود را با Sigma در میان بگذارید تا مسیر عملیاتی مناسب ترسیم شود.",
    talkToSigma: "گفت‌وگو با Sigma",
    exploreAllServices: "مشاهده همه خدمات",
    callsToAction: "فراخوان‌های اقدام",
  },
  AR: {
    home: "الرئيسية",
    services: "الخدمات",
    introduction: "مقدمة",
    service: "الخدمة",
    primaryCapabilities: "القدرات الأساسية",
    routes: "المسارات",
    exploreRoute: "استكشف المسار",
    serviceDisclaimer: "إخلاء مسؤولية الخدمة",
    placeholderNote: "ستُضاف تفاصيل الخدمة الكاملة والتصميم النهائي للصفحة بعد إكمال قالب الخدمة المعتمد.",
    serviceDetail: "تفاصيل الخدمة",
    reference: "مرجع",
    detailsAtAGlance: "ملخص تفاصيل الخدمة",
    nextStep: "الخطوة التالية",
    buildGrowthInfrastructure: "ابنِ بنية النمو المناسبة مع Sigma",
    shareProductMarketsConstraints: "شارك منتجك وأسواقك وقيودك كي ترسم Sigma المسار التشغيلي المناسب.",
    talkToSigma: "تحدث مع Sigma",
    exploreAllServices: "استكشف كل الخدمات",
    callsToAction: "دعوات الإجراء",
  },
  RU: {
    home: "Главная",
    services: "Сервисы",
    introduction: "Введение",
    service: "Сервис",
    primaryCapabilities: "Основные возможности",
    routes: "Маршруты",
    exploreRoute: "Открыть маршрут",
    serviceDisclaimer: "Отказ от ответственности по услуге",
    placeholderNote: "Полное содержание услуги и финальный дизайн страницы будут добавлены после завершения утверждённого шаблона услуги.",
    serviceDetail: "Детали сервиса",
    reference: "Справка",
    detailsAtAGlance: "Кратко о сервисе",
    nextStep: "Следующий шаг",
    buildGrowthInfrastructure: "Постройте правильную инфраструктуру роста с Sigma",
    shareProductMarketsConstraints: "Расскажите о продукте, рынках и ограничениях, чтобы Sigma определила подходящий операционный путь.",
    talkToSigma: "Связаться с Sigma",
    exploreAllServices: "Все сервисы",
    callsToAction: "Призывы к действию",
  },
  ES: {
    home: "Inicio",
    services: "Servicios",
    introduction: "Introducción",
    service: "Servicio",
    primaryCapabilities: "Capacidades principales",
    routes: "Rutas",
    exploreRoute: "Explorar ruta",
    serviceDisclaimer: "Aviso de servicio",
    placeholderNote: "El contenido completo del servicio y el diseño final de la página se añadirán después de completar la plantilla de servicio aprobada.",
    serviceDetail: "Detalle del servicio",
    reference: "Referencia",
    detailsAtAGlance: "Detalles del servicio de un vistazo",
    nextStep: "Siguiente paso",
    buildGrowthInfrastructure: "Construye la infraestructura de crecimiento adecuada con Sigma",
    shareProductMarketsConstraints: "Comparte tu producto, mercados y restricciones para que Sigma defina el camino operativo adecuado.",
    talkToSigma: "Hablar con Sigma",
    exploreAllServices: "Explorar todos los servicios",
    callsToAction: "Llamadas a la acción",
  },
  ZH: {
    home: "首页",
    services: "服务",
    introduction: "简介",
    service: "服务",
    primaryCapabilities: "核心能力",
    routes: "路径",
    exploreRoute: "查看路径",
    serviceDisclaimer: "服务免责声明",
    placeholderNote: "完整服务内容与最终页面设计将在批准的服务模板完成后加入。",
    serviceDetail: "服务详情",
    reference: "参考",
    detailsAtAGlance: "服务详情概览",
    nextStep: "下一步",
    buildGrowthInfrastructure: "与 Sigma 构建正确的增长基础设施",
    shareProductMarketsConstraints: "分享您的产品、市场与限制条件，让 Sigma 为您规划合适的运营路径。",
    talkToSigma: "联系 Sigma",
    exploreAllServices: "查看全部服务",
    callsToAction: "行动入口",
  },
};

const titles: Record<LangCode, Record<FinalServiceSlug, string>> = {
  EN: {
    "web3-business-development-strategic-partnerships": "Web3 Business Development & Strategic Partnerships",
    "kol-influencer-marketing": "KOL & Influencer Marketing",
    "crypto-exchange-growth-market-development": "Crypto Exchange Growth & Market Development",
    "web3-growth-strategy-market-expansion": "Web3 Growth Strategy & Market Expansion",
    "affiliate-partner-program-management": "Affiliate & Partner Program Management",
    "web3-marketing-strategy-campaign-management": "Web3 Marketing Strategy & Campaign Management",
    "community-management": "Community Management",
    "web3-content-social-media-marketing": "Web3 Content & Social Media Marketing",
    "web3-branding-personal-brand-development": "Web3 Branding & Personal Brand Development",
    "pr-media-relations": "PR & Media Relations",
    "seo-ai-search-optimization": "SEO & AI Search Optimization",
    "web3-market-research-competitive-intelligence": "Web3 Market Research & Competitive Intelligence",
    "exchange-listing-readiness-partner-introductions": "Exchange Listing Readiness & Partner Introductions",
    "web3-crm-automation-product-solutions": "Web3 CRM, Automation & Product Solutions",
    "web3-ecosystem-strategy-advisory": "Web3 Ecosystem Strategy & Advisory",
  },
  FA: {
    "web3-business-development-strategic-partnerships": "توسعه کسب‌وکار وب۳ و مشارکت‌های استراتژیک",
    "kol-influencer-marketing": "مارکتینگ KOL و اینفلوئنسر",
    "crypto-exchange-growth-market-development": "رشد صرافی کریپتو و توسعه بازار",
    "web3-growth-strategy-market-expansion": "استراتژی رشد وب۳ و توسعه بازار",
    "affiliate-partner-program-management": "مدیریت برنامه‌های افیلیت و شرکا",
    "web3-marketing-strategy-campaign-management": "استراتژی مارکتینگ وب۳ و مدیریت کمپین",
    "community-management": "مدیریت کامیونیتی",
    "web3-content-social-media-marketing": "محتوای وب۳ و مارکتینگ شبکه‌های اجتماعی",
    "web3-branding-personal-brand-development": "برندینگ وب۳ و توسعه برند شخصی",
    "pr-media-relations": "روابط عمومی و رسانه",
    "seo-ai-search-optimization": "SEO و بهینه‌سازی جست‌وجوی هوش مصنوعی",
    "web3-market-research-competitive-intelligence": "تحقیقات بازار وب۳ و هوش رقابتی",
    "exchange-listing-readiness-partner-introductions": "آمادگی لیستینگ صرافی و معرفی شرکا",
    "web3-crm-automation-product-solutions": "CRM وب۳، اتوماسیون و راهکارهای محصول",
    "web3-ecosystem-strategy-advisory": "استراتژی اکوسیستم وب۳ و مشاوره",
  },
  AR: {
    "web3-business-development-strategic-partnerships": "تطوير أعمال Web3 والشراكات الاستراتيجية",
    "kol-influencer-marketing": "تسويق KOL والمؤثرين",
    "crypto-exchange-growth-market-development": "نمو منصات العملات المشفرة وتطوير الأسواق",
    "web3-growth-strategy-market-expansion": "استراتيجية نمو Web3 وتوسّع الأسواق",
    "affiliate-partner-program-management": "إدارة برامج الشركاء والإحالة",
    "web3-marketing-strategy-campaign-management": "استراتيجية تسويق Web3 وإدارة الحملات",
    "community-management": "إدارة المجتمعات",
    "web3-content-social-media-marketing": "محتوى Web3 وتسويق وسائل التواصل الاجتماعي",
    "web3-branding-personal-brand-development": "بناء علامة Web3 وتطوير العلامة الشخصية",
    "pr-media-relations": "العلاقات العامة والإعلام",
    "seo-ai-search-optimization": "SEO وتحسين البحث بالذكاء الاصطناعي",
    "web3-market-research-competitive-intelligence": "أبحاث أسواق Web3 والذكاء التنافسي",
    "exchange-listing-readiness-partner-introductions": "الاستعداد للإدراج والتعريف بالشركاء",
    "web3-crm-automation-product-solutions": "CRM و الأتمتة وحلول منتجات Web3",
    "web3-ecosystem-strategy-advisory": "استراتيجية منظومة Web3 والاستشارات",
  },
  RU: {
    "web3-business-development-strategic-partnerships": "Развитие Web3-бизнеса и стратегические партнёрства",
    "kol-influencer-marketing": "Маркетинг KOL и инфлюенсеров",
    "crypto-exchange-growth-market-development": "Рост криптобиржи и развитие рынка",
    "web3-growth-strategy-market-expansion": "Стратегия роста Web3 и выход на рынки",
    "affiliate-partner-program-management": "Управление affiliate- и партнёрскими программами",
    "web3-marketing-strategy-campaign-management": "Маркетинговая стратегия Web3 и управление кампаниями",
    "community-management": "Управление сообществами",
    "web3-content-social-media-marketing": "Web3-контент и маркетинг в соцсетях",
    "web3-branding-personal-brand-development": "Брендинг Web3 и развитие личного бренда",
    "pr-media-relations": "PR и связи с медиа",
    "seo-ai-search-optimization": "SEO и оптимизация поиска с ИИ",
    "web3-market-research-competitive-intelligence": "Исследование Web3-рынков и конкурентная разведка",
    "exchange-listing-readiness-partner-introductions": "Подготовка к листингу и представление партнёров",
    "web3-crm-automation-product-solutions": "Web3 CRM, автоматизация и продуктовые решения",
    "web3-ecosystem-strategy-advisory": "Стратегия Web3-экосистемы и консалтинг",
  },
  ES: {
    "web3-business-development-strategic-partnerships": "Desarrollo de negocio Web3 y alianzas estratégicas",
    "kol-influencer-marketing": "Marketing de KOL e influencers",
    "crypto-exchange-growth-market-development": "Crecimiento de exchanges cripto y desarrollo de mercados",
    "web3-growth-strategy-market-expansion": "Estrategia de crecimiento Web3 y expansión de mercados",
    "affiliate-partner-program-management": "Gestión de programas de afiliados y partners",
    "web3-marketing-strategy-campaign-management": "Estrategia de marketing Web3 y gestión de campañas",
    "community-management": "Gestión de comunidades",
    "web3-content-social-media-marketing": "Contenido Web3 y marketing en redes sociales",
    "web3-branding-personal-brand-development": "Branding Web3 y desarrollo de marca personal",
    "pr-media-relations": "Relaciones públicas y medios",
    "seo-ai-search-optimization": "SEO y optimización de búsqueda con IA",
    "web3-market-research-competitive-intelligence": "Investigación de mercados Web3 e inteligencia competitiva",
    "exchange-listing-readiness-partner-introductions": "Preparación para listings y presentación de partners",
    "web3-crm-automation-product-solutions": "CRM Web3, automatización y soluciones de producto",
    "web3-ecosystem-strategy-advisory": "Estrategia de ecosistema Web3 y asesoría",
  },
  ZH: {
    "web3-business-development-strategic-partnerships": "Web3 业务发展与战略合作",
    "kol-influencer-marketing": "KOL 与影响者营销",
    "crypto-exchange-growth-market-development": "加密交易平台增长与市场发展",
    "web3-growth-strategy-market-expansion": "Web3 增长战略与市场扩张",
    "affiliate-partner-program-management": "联盟与合作伙伴计划管理",
    "web3-marketing-strategy-campaign-management": "Web3 营销策略与活动管理",
    "community-management": "社群管理",
    "web3-content-social-media-marketing": "Web3 内容与社交媒体营销",
    "web3-branding-personal-brand-development": "Web3 品牌与个人品牌发展",
    "pr-media-relations": "公关与媒体关系",
    "seo-ai-search-optimization": "SEO 与 AI 搜索优化",
    "web3-market-research-competitive-intelligence": "Web3 市场研究与竞争情报",
    "exchange-listing-readiness-partner-introductions": "交易平台上架准备与合作伙伴引荐",
    "web3-crm-automation-product-solutions": "Web3 CRM、自动化与产品解决方案",
    "web3-ecosystem-strategy-advisory": "Web3 生态战略与咨询",
  },
};

export function getFinalServiceTitle(slug: FinalServiceSlug, lang: LangCode): string {
  return titles[lang]?.[slug] ?? titles.EN[slug];
}

export const serviceDisclaimerByLang: Record<LangCode, string> = {
  EN: "Sigmaa provides B2B marketing, growth, technology, research and business-development services. Sigmaa does not provide investment advice, execute transactions, hold customer assets, operate as a broker or market maker, solicit investments, or guarantee listings, liquidity, trading activity or commercial outcomes. Certain services are subject to client eligibility, applicable regulations, target-market restrictions and third-party approval.",
  FA: "Sigmaa خدمات مارکتینگ B2B، رشد، فناوری، پژوهش و توسعه کسب‌وکار ارائه می‌دهد. Sigmaa مشاوره سرمایه‌گذاری نمی‌دهد، معامله اجرا نمی‌کند، دارایی مشتری را نگهداری نمی‌کند، به‌عنوان بروکر یا مارکت‌میکر فعالیت ندارد، برای سرمایه‌گذاری درخواست نمی‌کند و لیستینگ، نقدینگی، فعالیت معاملاتی یا نتیجه تجاری را تضمین نمی‌کند. برخی خدمات مشروط به صلاحیت مشتری، مقررات قابل‌اعمال، محدودیت‌های بازار هدف و تأیید طرف ثالث هستند.",
  AR: "تقدم Sigmaa خدمات التسويق بين الشركات والنمو والتقنية والبحث وتطوير الأعمال. لا تقدم Sigmaa نصائح استثمارية، ولا تنفذ معاملات، ولا تحتفظ بأصول العملاء، ولا تعمل كوسيط أو صانع سوق، ولا تستقطب الاستثمارات، ولا تضمن الإدراج أو السيولة أو نشاط التداول أو النتائج التجارية. تخضع بعض الخدمات لأهلية العميل واللوائح المعمول بها وقيود السوق المستهدف وموافقة الأطراف الثالثة.",
  RU: "Sigmaa оказывает B2B-услуги в области маркетинга, роста, технологий, исследований и развития бизнеса. Sigmaa не предоставляет инвестиционные рекомендации, не исполняет сделки, не хранит активы клиентов, не работает как брокер или маркет-мейкер, не привлекает инвестиции и не гарантирует листинги, ликвидность, торговую активность или коммерческие результаты. Некоторые услуги зависят от соответствия клиента требованиям, применимых правил, ограничений целевого рынка и одобрения третьих сторон.",
  ES: "Sigmaa presta servicios B2B de marketing, crecimiento, tecnología, investigación y desarrollo de negocio. Sigmaa no ofrece asesoramiento de inversión, ejecuta transacciones, custodia activos de clientes, opera como broker o market maker, solicita inversiones ni garantiza listings, liquidez, actividad de trading o resultados comerciales. Algunos servicios dependen de la elegibilidad del cliente, la normativa aplicable, las restricciones del mercado objetivo y la aprobación de terceros.",
  ZH: "Sigmaa 提供 B2B 营销、增长、技术、研究与业务发展服务。Sigmaa 不提供投资建议，不执行交易，不持有客户资产，不作为经纪商或做市商运营，不招揽投资，也不保证上架、流动性、交易活动或商业结果。部分服务受客户资格、适用法规、目标市场限制及第三方批准约束。",
};
